### ISSUE TITLE
python-requirements.txt does not exist

### ISSUE THREAD

**Issue by jhanarato** [suttacentral/next-sc#204]
Working through the [developer setup](https://github.com/suttacentral/next-sc/wiki/Developer-Setup) docs I come across the instruction to run this command:

`pip install -r python-requirements.txt`

This does not seem to exist anymore.

**Comment by gradam** [comment]
Hi @jhanarato. This page is outdated. Please use[ instructions from README](https://github.com/suttacentral/next-sc#11-running-the-project) instead.
