### ISSUE TITLE
Add Slovenian texts

### ISSUE THREAD

**Issue by sujato** [suttacentral/next-sc#514]
Ajahn Hiriko gave us permission to add his translations in Slovenian. We should add these when we get the time.

http://slo-theravada.org/ucenja/sutta.html

**Comment by SamaneriVimala** [comment]
Good. I was looking for something for one of our volunteers to do.
But ... maybe next time you can let me know. I only stumbled on this issue by accident and did not know it existed.

**Comment by SamaneriVimala** [comment]
Moved to Alfred.
