### ISSUE TITLE
Licensing details for next-sc assets, etc.

### ISSUE THREAD

**Issue by sujato** [suttacentral/next-sc#86]
### Difficulty icons
CC by 3.0 https://creativecommons.org/licenses/by/3.0/us/
Note: Noun project svgs have the artist in the SVG file.

**Comment by TrebuhD** [comment]
Disconnected cloud icon by Bernar Novalyi from the Noun Project.

**Comment by sujato** [comment]
Artist Kim Hoa Tram (kim.hoatram@yahoo.com.au) gives permission for the use of his images on the website, as per email on 20 Nov 2017.

This confirms the advice by Julia.Rodwell (Julia.Rodwell@ngv.vic.gov.au) of the National Gallery of Victoria by email to sujato@gmail.com on 17 Nov 2017: "If the artist is happy for you to use the works, you are welcome to take the images from our site."
